// Literal argv captured from the unmodified codexExecArgs before extraction.
// Do not regenerate using encodeCodexPolicy. Includes all policy axes and effort levels.
import { describe, expect, it } from "vitest";
import { codexExecArgs, assertCodexSandboxAllowed } from "../../src/connectors/codex.js";
import type { SandboxPolicy } from "../../src/config/types.js";

const defaultArgv = ["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work","-"];
const frozen: Array<{name: string; model: string; cwd: string; policy: SandboxPolicy; argv: string[]}> = [
  {"name":"read-only network=false never effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":[],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=false never effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=false never effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=false never effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=false never effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=false never effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=false on-request effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":[],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=false on-request effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=false on-request effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=false on-request effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=false on-request effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=false on-request effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=false untrusted effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":[],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=false untrusted effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=false untrusted effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=false untrusted effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=false untrusted effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=false untrusted effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=false on-failure effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":[],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=false on-failure effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=false on-failure effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=false on-failure effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=false on-failure effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=false on-failure effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=true never effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":[],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=true never effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=true never effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=true never effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=true never effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=true never effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=true on-request effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":[],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=true on-request effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=true on-request effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=true on-request effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=true on-request effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=true on-request effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=true untrusted effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":[],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=true untrusted effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=true untrusted effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=true untrusted effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=true untrusted effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=true untrusted effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"read-only network=true on-failure effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":[],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"read-only network=true on-failure effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"read-only network=true on-failure effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"read-only network=true on-failure effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"read-only network=true on-failure effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"read-only network=true on-failure effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"read-only","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","read-only","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=false never effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":[],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=false never effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=false never effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=false never effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=false never effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=false never effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=false on-request effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":[],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=false on-request effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=false on-request effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=false on-request effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=false on-request effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=false on-request effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=false untrusted effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":[],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=false untrusted effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=false untrusted effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=false untrusted effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=false untrusted effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=false untrusted effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=false on-failure effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":[],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=false on-failure effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=false on-failure effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=false on-failure effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=false on-failure effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=false on-failure effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=true never effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":[],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=true never effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=true never effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=true never effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=true never effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=true never effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=true on-request effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":[],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=true on-request effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=true on-request effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=true on-request effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=true on-request effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=true on-request effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=true untrusted effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":[],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=true untrusted effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=true untrusted effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=true untrusted effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=true untrusted effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=true untrusted effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"workspace-write network=true on-failure effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":[],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"workspace-write network=true on-failure effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"workspace-write network=true on-failure effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"workspace-write network=true on-failure effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"workspace-write network=true on-failure effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"workspace-write network=true on-failure effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"workspace-write","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","workspace-write","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=false never effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":[],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=false never effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=false never effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=false never effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=false never effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=false never effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=false on-request effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":[],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=false on-request effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=false on-request effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=false on-request effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=false on-request effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=false on-request effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=false untrusted effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":[],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=false untrusted effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=false untrusted effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=false untrusted effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=false untrusted effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=false untrusted effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=false on-failure effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":[],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=false on-failure effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=false on-failure effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=false on-failure effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=false on-failure effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=false on-failure effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":false,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=false","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=true never effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":[],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=true never effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=true never effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=true never effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=true never effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=true never effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"never"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"never\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=true on-request effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":[],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=true on-request effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=true on-request effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=true on-request effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=true on-request effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=true on-request effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-request"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-request\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=true untrusted effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":[],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=true untrusted effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=true untrusted effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=true untrusted effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=true untrusted effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=true untrusted effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"untrusted"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"untrusted\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]},
  {"name":"danger-full-access network=true on-failure effort=omitted","model":"gpt-6-luna","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":[],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-"]},
  {"name":"danger-full-access network=true on-failure effort=minimal","model":"gpt-6-luna/minimal","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"minimal\"","-"]},
  {"name":"danger-full-access network=true on-failure effort=low","model":"gpt-6-luna/low","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"low\"","-"]},
  {"name":"danger-full-access network=true on-failure effort=medium","model":"gpt-6-luna/medium","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"medium\"","-"]},
  {"name":"danger-full-access network=true on-failure effort=high","model":"gpt-6-luna/high","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"high\"","-"]},
  {"name":"danger-full-access network=true on-failure effort=xhigh","model":"gpt-6-luna/xhigh","cwd":"/work with spaces/\"quoted\"\\path","policy":{"filesystemMode":"danger-full-access","networkAccess":true,"writableRoots":["/root with spaces","/quote\"and\\backslash"],"approvalPolicy":"on-failure"},"argv":["exec","--json","--skip-git-repo-check","--sandbox","danger-full-access","-c","sandbox_workspace_write.network_access=true","-c","sandbox_workspace_write.writable_roots=[\"/root with spaces\",\"/quote\\\"and\\\\backslash\"]","-c","approval_policy=\"on-failure\"","-m","gpt-6-luna","-C","/work with spaces/\"quoted\"\\path","-c","model_reasoning_effort=\"xhigh\"","-"]}
];

describe("AC02 frozen pre-refactor exec argv", () => {
  it("preserves public defaults", () => expect(codexExecArgs("gpt-6-luna", "/work")).toEqual(defaultArgv));
  it.each(frozen)("byte-identical: $name", ({model,cwd,policy,argv}) => {
    expect(Buffer.from(JSON.stringify(codexExecArgs(model,cwd,policy.filesystemMode,policy)))).toEqual(Buffer.from(JSON.stringify(argv)));
  });
});

import { encodeCodexPolicy } from "../../src/connectors/codex-policy.js";

describe("AC02 app-server policy placement", () => {
  it.each(frozen)("section 4 payload: $name", ({model,cwd,policy}) => {
    if (policy.approvalPolicy === "on-failure") {
      expect(() => encodeCodexPolicy(model,cwd,policy,"app-server")).toThrow(/app-server.*on-failure/);
      return;
    }
    const effort = model.includes("/") ? model.split("/")[1] : undefined;
    const result = encodeCodexPolicy(model,cwd,policy,"app-server");
    expect(result).toEqual({
      thread:{model:"gpt-6-luna",cwd,approvalPolicy:policy.approvalPolicy,sandbox:policy.filesystemMode,
        ...(policy.filesystemMode === "workspace-write" ? {config:{
          "sandbox_workspace_write.network_access":policy.networkAccess,
          "sandbox_workspace_write.writable_roots":[...policy.writableRoots],
        }} : {})},
      turn:effort ? {effort} : {},
    });
    expect(JSON.stringify(result)).not.toMatch(/sandboxPolicy|exclude/i);
    const exec = encodeCodexPolicy(model,cwd,policy,"exec");
    const workspaceConfig = Object.fromEntries(exec.flatMap((arg, i) => {
      const entry = exec[i + 1];
      if (arg !== "-c" || !entry?.startsWith("sandbox_workspace_write.")) return [];
      const equals = entry.indexOf("=");
      return [[entry.slice(0, equals), JSON.parse(entry.slice(equals + 1))]];
    }));
    if (policy.filesystemMode === "workspace-write") expect(result.thread.config).toEqual(workspaceConfig);
    else expect(result.thread).not.toHaveProperty("config");
    if (!effort) expect(result.turn).not.toHaveProperty("effort");
  });
  it("retains full-access authorization at the dispatch boundary", () => {
    expect(() => assertCodexSandboxAllowed("danger-full-access",{})).toThrow(/ALLOW_FULL_ACCESS/);
    expect(() => assertCodexSandboxAllowed("danger-full-access",{STRATUM_CODEX_ALLOW_FULL_ACCESS:"1"})).not.toThrow();
    expect(encodeCodexPolicy("gpt-6-luna","/work",{filesystemMode:"danger-full-access",networkAccess:false,writableRoots:[],approvalPolicy:"never"},"app-server").thread.sandbox).toBe("danger-full-access");
  });
  it("keeps an unrecognized effort suffix in the model name", () => {
    expect(encodeCodexPolicy("vendor/model/unknown","/work",{filesystemMode:"read-only",networkAccess:false,writableRoots:[],approvalPolicy:"never"},"app-server")).toEqual({thread:{model:"vendor/model/unknown",cwd:"/work",approvalPolicy:"never",sandbox:"read-only"},turn:{}});
  });
});
